In [1]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)          # keep sane in notebooks
pd.set_option("display.max_colwidth", None)
pd.set_option("display.expand_frame_repr", False)


df = pd.read_csv(f"c:/Users/goku/Documents/NFL_ML_Predictions/backend/data/datasets/game_features_20260102.csv")
df.info()
print(df.columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3284 entries, 0 to 3283
Columns: 238 entries, season to away_team_WAS
dtypes: float64(167), object(71)
memory usage: 6.0+ MB
Index(['season', 'week', 'game_id', 'home_game_date', 'home_team', 'away_team',
       'home_points_for', 'away_points_for', 'point_diff', 'winner',
       ...
       'away_team_NO', 'away_team_NYG', 'away_team_NYJ', 'away_team_PHI',
       'away_team_PIT', 'away_team_SEA', 'away_team_SF', 'away_team_TB',
       'away_team_TEN', 'away_team_WAS'],
      dtype='object', length=238)

In [2]:
df.head()

   season  week          game_id home_game_date home_team away_team  home_points_for  away_points_for  point_diff winner  home_prior_pf_avg_3  home_prior_pa_avg_3  home_prior_win_pct_3  home_prior_away_moneyline_3  home_prior_home_moneyline_3  home_prior_spread_line_3  home_prior_total_line_3  home_prior_away_rest_3  home_prior_home_rest_3  home_prior_off_epa_per_play_3  home_prior_off_success_rate_3  home_prior_off_explosive_rate_3  home_prior_off_turnover_rate_3  home_prior_def_success_rate_allowed_3  home_prior_def_explosive_rate_allowed_3  home_prior_def_epa_per_play_3  home_prior_def_takeaway_rate_3  home_prior_pf_avg_5  home_prior_pa_avg_5  home_prior_win_pct_5  home_prior_away_moneyline_5  home_prior_home_moneyline_5  home_prior_spread_line_5  home_prior_total_line_5  home_prior_away_rest_5  home_prior_home_rest_5  home_prior_off_epa_per_play_5  home_prior_off_success_rate_5  home_prior_off_explosive_rate_5  home_prior_off_turnover_rate_5  home_prior_def_success_rate_allowed_5  home_prior_def_explosive_rate_allowed_5  home_prior_def_epa_per_play_5  home_prior_def_takeaway_rate_5  away_prior_pf_avg_3  away_prior_pa_avg_3  away_prior_win_pct_3  away_prior_away_moneyline_3  away_prior_home_moneyline_3  away_prior_spread_line_3  away_prior_total_line_3  away_prior_away_rest_3  away_prior_home_rest_3  away_prior_off_epa_per_play_3  away_prior_off_success_rate_3  away_prior_off_explosive_rate_3  away_prior_off_turnover_rate_3  away_prior_def_success_rate_allowed_3  away_prior_def_explosive_rate_allowed_3  away_prior_def_epa_per_play_3  away_prior_def_takeaway_rate_3  away_prior_pf_avg_5  away_prior_pa_avg_5  away_prior_win_pct_5  away_prior_away_moneyline_5  away_prior_home_moneyline_5  away_prior_spread_line_5  away_prior_total_line_5  away_prior_away_rest_5  away_prior_home_rest_5  away_prior_off_epa_per_play_5  away_prior_off_success_rate_5  away_prior_off_explosive_rate_5  away_prior_off_turnover_rate_5  away_prior_def_success_rate_allowed_5  away_prior_def_explosive_rate_allowed_5  away_prior_def_epa_per_play_5  away_prior_def_takeaway_rate_5  home_minus_away_pf_avg_3  home_minus_away_pa_avg_3  home_minus_away_win_pct_3  home_minus_away_away_moneyline_3  home_minus_away_home_moneyline_3  home_minus_away_spread_line_3  home_minus_away_total_line_3  home_minus_away_away_rest_3  home_minus_away_home_rest_3  home_minus_away_off_epa_per_play_3  home_minus_away_off_success_rate_3  home_minus_away_off_explosive_rate_3  home_minus_away_off_turnover_rate_3  home_minus_away_def_success_rate_allowed_3  home_minus_away_def_explosive_rate_allowed_3  home_minus_away_def_epa_per_play_3  home_minus_away_def_takeaway_rate_3  home_minus_away_pf_avg_5  home_minus_away_pa_avg_5  home_minus_away_win_pct_5  home_minus_away_away_moneyline_5  home_minus_away_home_moneyline_5  home_minus_away_spread_line_5  home_minus_away_total_line_5  home_minus_away_away_rest_5  home_minus_away_home_rest_5  home_minus_away_off_epa_per_play_5  home_minus_away_off_success_rate_5  home_minus_away_off_explosive_rate_5  home_minus_away_off_turnover_rate_5  home_minus_away_def_success_rate_allowed_5  home_minus_away_def_explosive_rate_allowed_5  home_minus_away_def_epa_per_play_5  home_minus_away_def_takeaway_rate_5  home_moneyline_prob  away_moneyline_prob  moneyline_prob_diff  spread_line  total_line  home_rest  away_rest  rest_diff  home_player_team_qb_pass_yards  home_player_team_qb_pass_tds  home_player_team_qb_completions  home_player_team_qb_attempts  home_player_team_qb_completion_pct  home_player_team_rb_rush_yards  home_player_team_rb_rush_tds  home_player_team_rb_receptions  home_player_team_rb_receiving_yards  home_player_team_wr_targets  home_player_team_wr_receptions  home_player_team_wr_receiving_yards  home_player_team_wr_receiving_tds  away_player_team_qb_pass_yards  away_player_team_qb_pass_tds  away_player_team_qb_completions  away_player_team_qb_attempts  away_player_team_qb_completion_pct  away_player_team_rb_rush_yards  away_player_team_rb_rush_tds  away_player_team_rb_receptions  away_player_team_rb_receiving_yards  away_player_team_wr_targets  away_player_team_wr_receptions  away_player_team_wr_receiving_yards  away_player_team_wr_receiving_tds has_home_team  home_elo_pre  away_elo_pre  elo_diff_pre  home_elo_post  away_elo_post  time_key  home_rolling_pf_3  home_rolling_pa_3  home_rolling_win_pct_3  home_rolling_pf_5  home_rolling_pa_5  home_rolling_win_pct_5  home_rolling_pf_10  home_rolling_pa_10  home_rolling_win_pct_10  away_rolling_pf_3  away_rolling_pa_3  away_rolling_win_pct_3  away_rolling_pf_5  away_rolling_pa_5  away_rolling_win_pct_5  away_rolling_pf_10  away_rolling_pa_10  away_rolling_win_pct_10  home_qb_completion_pct  away_qb_completion_pct home_win home_team_ARI home_team_ATL home_team_BAL home_team_BUF home_team_CAR home_team_CHI home_team_CIN home_team_CLE home_team_DAL home_team_DEN home_team_DET home_team_GB home_team_HOU home_team_IND home_team_JAX home_team_KC home_team_LAC home_team_LAR home_team_LV home_team_MIA home_team_MIN home_team_NE home_team_NO home_team_NYG home_team_NYJ home_team_PHI home_team_PIT home_team_SEA home_team_SF home_team_TB home_team_TEN home_team_WAS away_team_ARI away_team_ATL away_team_BAL away_team_BUF away_team_CAR away_team_CHI away_team_CIN away_team_CLE away_team_DAL away_team_DEN away_team_DET away_team_GB away_team_HOU away_team_IND away_team_JAX away_team_KC away_team_LAC away_team_LAR away_team_LV away_team_MIA away_team_MIN away_team_NE away_team_NO away_team_NYG away_team_NYJ away_team_PHI away_team_PIT away_team_SEA away_team_SF away_team_TB away_team_TEN away_team_WAS
0  2014.0   1.0  2014_01_BUF_CHI     2014-09-07       CHI       BUF             20.0             23.0        -3.0    BUF                  0.0                  0.0                   0.0                          0.0                          0.0                       0.0                      0.0                     0.0                     0.0                            0.0                            0.0                              0.0                             0.0                                    0.0                                      0.0                            0.0                             0.0                  0.0                  0.0                   0.0                          0.0                          0.0                       0.0                      0.0                     0.0                     0.0                            0.0                            0.0                              0.0                             0.0                                    0.0                                      0.0                            0.0                             0.0                  0.0                  0.0                   0.0                          0.0                          0.0                       0.0                      0.0                     0.0                     0.0                            0.0                            0.0                              0.0                             0.0                                    0.0                                      0.0                            0.0                             0.0                  0.0                  0.0                   0.0                          0.0                          0.0                       0.0                      0.0                     0.0                     0.0                            0.0                            0.0                              0.0                             0.0                                    0.0                                      0.0                            0.0                             0.0                       NaN                       NaN                        NaN                               NaN                               NaN                            NaN                           NaN                          NaN                          NaN                                 NaN                                 NaN                                   NaN                                  NaN                                         NaN                                           NaN                                 NaN                                  NaN                       NaN                       NaN                        NaN                               NaN                               NaN                            NaN                           NaN                          NaN                          NaN                                 NaN                                 NaN                                   NaN                                  NaN                                         NaN                                           NaN                                 NaN                                  NaN             0.729730             0.294985             0.434744          7.0        47.0        7.0        7.0        0.0                           349.0                           2.0                             34.0                          49.0                            0.693878                            86.0                           0.0                             8.0                                 87.0                         40.0                            26.0                                262.0                                2.0                           173.0                           1.0                             16.0                          22.0                            0.727273                           174.0                           0.0                             6.0                                 24.0                         15.0                             9.0                                145.0                                0.0          True        1500.0        1500.0           0.0         1484.0         1516.0  201401.0                NaN                NaN                     NaN                NaN                NaN                     NaN                 NaN                 NaN                      NaN                NaN                NaN                     NaN                NaN                NaN                     NaN                 NaN                 NaN                      NaN                0.693878                0.727273    False         False         False         False         False         False          True         False         False         False         False         False        False         False         False         False        False         False         False        False         False         False        False        False         False         False         False         False         False        False        False         False         False         False         False         False          True         False         False         False         False         False         False         False        False         False         False         False        False         False         False        False         False         False        False        False         False         False         False         False         False        False        False         False         False
1  2014.0   1.0   2014_01_CAR_TB     2014-09-07        TB       CAR             14.0             20.0        -6.0    CAR                  0.0                  0.0                   0.0                          0.0                          0.0                       0.0                      0.0                     0.0                     0.0                            0.0                            0.0                              0.0                             0.0                                    0.0                                      0.0                            0.0                             0.0                  0.0                  0.0                   0.0                          0.0                          0.0                       0.0                      0.0                     0.0                     0.0                            0.0                            0.0                              0.0                             0.0                                    0.0                                      0.0                            0.0                             0.0                  0.0                  0.0                   0.0                          0.0                          0.0                       0.0                      0.0                     0.0                     0.0                            0.0                            0.0                              0.0                             0.0                                    0.0                                      0.0                            0.0                             0.0                  0.0                  0.0                   0.0                          0.0                          0.0                       0.0                      0.0                     0.0                     0.0                            0.0                            0.0                              0.0                             0.0                                    0.0                                      0.0                            0.0                             0.0                       NaN                       NaN                        NaN                               NaN                               NaN                            NaN                           NaN                          NaN                          NaN                                 NaN                                 NaN                                   NaN                                  NaN                                         NaN                                           NaN                                 NaN                                  NaN                       NaN                       NaN                        NaN                               NaN                               NaN                            NaN                           NaN                          NaN                          NaN                                 NaN                                 NaN                                   NaN                                  NaN                                         NaN                                           NaN                                 NaN                                  NaN             0.692308             0.332226             0.360082          5.5        38.5        7.0        7.0        0.0                           183.0                           2.0                             22.0                          35.0                            0.628571                            21.0                           0.0                             3.0                                 15.0                         31.0                            19.0                                168.0                                1.0                           230.0                           2.0                             24.0                          34.0                            0.705882                            92.0                           0.0                             3.0                                 17.0                         24.0                            19.0                                207.0                                2.0          True        1500.0        1500.0           0.0         1484.0         1516.0  201401.0                NaN                NaN                     NaN                NaN                NaN                     NaN                 NaN                 NaN                      NaN                NaN                NaN                     NaN                NaN                NaN                     NaN                 NaN                 NaN                      NaN                0.628571                0.705882    False         False         False         False         False         False         False         False         False         False         False         False        False         False         False         False        False         False         False        False         False         False        False        False         False         False         False         False         False        False         True         False         False         False         False         False         False          True         False         False         False         False         False         False        False         False         False         False        False         False         False        False         False         False        False        False         False         False         False         False         False        False        False         False         False

In [10]:
df = df.infer_objects()
df.info()
df = df.sort_values(by=["season", "week", "home_game_date"],ascending=[False, False, False])
df = df.reset_index(drop=True)
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3284 entries, 0 to 3283
Columns: 238 entries, season to away_team_WAS
dtypes: float64(167), object(71)
memory usage: 6.0+ MB

   season  week          game_id home_game_date home_team away_team  home_points_for  away_points_for  point_diff winner  home_prior_pf_avg_3  home_prior_pa_avg_3  home_prior_win_pct_3  home_prior_away_moneyline_3  home_prior_home_moneyline_3  home_prior_spread_line_3  home_prior_total_line_3  home_prior_away_rest_3  home_prior_home_rest_3  home_prior_off_epa_per_play_3  home_prior_off_success_rate_3  home_prior_off_explosive_rate_3  home_prior_off_turnover_rate_3  home_prior_def_success_rate_allowed_3  home_prior_def_explosive_rate_allowed_3  home_prior_def_epa_per_play_3  home_prior_def_takeaway_rate_3  home_prior_pf_avg_5  home_prior_pa_avg_5  home_prior_win_pct_5  home_prior_away_moneyline_5  home_prior_home_moneyline_5  home_prior_spread_line_5  home_prior_total_line_5  home_prior_away_rest_5  home_prior_home_rest_5  home_prior_off_epa_per_play_5  home_prior_off_success_rate_5  home_prior_off_explosive_rate_5  home_prior_off_turnover_rate_5  home_prior_def_success_rate_allowed_5  home_prior_def_explosive_rate_allowed_5  home_prior_def_epa_per_play_5  home_prior_def_takeaway_rate_5  away_prior_pf_avg_3  away_prior_pa_avg_3  away_prior_win_pct_3  away_prior_away_moneyline_3  away_prior_home_moneyline_3  away_prior_spread_line_3  away_prior_total_line_3  away_prior_away_rest_3  away_prior_home_rest_3  away_prior_off_epa_per_play_3  away_prior_off_success_rate_3  away_prior_off_explosive_rate_3  away_prior_off_turnover_rate_3  away_prior_def_success_rate_allowed_3  away_prior_def_explosive_rate_allowed_3  away_prior_def_epa_per_play_3  away_prior_def_takeaway_rate_3  away_prior_pf_avg_5  away_prior_pa_avg_5  away_prior_win_pct_5  away_prior_away_moneyline_5  away_prior_home_moneyline_5  away_prior_spread_line_5  away_prior_total_line_5  away_prior_away_rest_5  away_prior_home_rest_5  away_prior_off_epa_per_play_5  away_prior_off_success_rate_5  away_prior_off_explosive_rate_5  away_prior_off_turnover_rate_5  away_prior_def_success_rate_allowed_5  away_prior_def_explosive_rate_allowed_5  away_prior_def_epa_per_play_5  away_prior_def_takeaway_rate_5  home_minus_away_pf_avg_3  home_minus_away_pa_avg_3  home_minus_away_win_pct_3  home_minus_away_away_moneyline_3  home_minus_away_home_moneyline_3  home_minus_away_spread_line_3  home_minus_away_total_line_3  home_minus_away_away_rest_3  home_minus_away_home_rest_3  home_minus_away_off_epa_per_play_3  home_minus_away_off_success_rate_3  home_minus_away_off_explosive_rate_3  home_minus_away_off_turnover_rate_3  home_minus_away_def_success_rate_allowed_3  home_minus_away_def_explosive_rate_allowed_3  home_minus_away_def_epa_per_play_3  home_minus_away_def_takeaway_rate_3  home_minus_away_pf_avg_5  home_minus_away_pa_avg_5  home_minus_away_win_pct_5  home_minus_away_away_moneyline_5  home_minus_away_home_moneyline_5  home_minus_away_spread_line_5  home_minus_away_total_line_5  home_minus_away_away_rest_5  home_minus_away_home_rest_5  home_minus_away_off_epa_per_play_5  home_minus_away_off_success_rate_5  home_minus_away_off_explosive_rate_5  home_minus_away_off_turnover_rate_5  home_minus_away_def_success_rate_allowed_5  home_minus_away_def_explosive_rate_allowed_5  home_minus_away_def_epa_per_play_5  home_minus_away_def_takeaway_rate_5  home_moneyline_prob  away_moneyline_prob  moneyline_prob_diff  spread_line  total_line  home_rest  away_rest  rest_diff  home_player_team_qb_pass_yards  home_player_team_qb_pass_tds  home_player_team_qb_completions  home_player_team_qb_attempts  home_player_team_qb_completion_pct  home_player_team_rb_rush_yards  home_player_team_rb_rush_tds  home_player_team_rb_receptions  home_player_team_rb_receiving_yards  home_player_team_wr_targets  home_player_team_wr_receptions  home_player_team_wr_receiving_yards  home_player_team_wr_receiving_tds  away_player_team_qb_pass_yards  away_player_team_qb_pass_tds  away_player_team_qb_completions  away_player_team_qb_attempts  away_player_team_qb_completion_pct  away_player_team_rb_rush_yards  away_player_team_rb_rush_tds  away_player_team_rb_receptions  away_player_team_rb_receiving_yards  away_player_team_wr_targets  away_player_team_wr_receptions  away_player_team_wr_receiving_yards  away_player_team_wr_receiving_tds has_home_team  home_elo_pre  away_elo_pre  elo_diff_pre  home_elo_post  away_elo_post  time_key  home_rolling_pf_3  home_rolling_pa_3  home_rolling_win_pct_3  home_rolling_pf_5  home_rolling_pa_5  home_rolling_win_pct_5  home_rolling_pf_10  home_rolling_pa_10  home_rolling_win_pct_10  away_rolling_pf_3  away_rolling_pa_3  away_rolling_win_pct_3  away_rolling_pf_5  away_rolling_pa_5  away_rolling_win_pct_5  away_rolling_pf_10  away_rolling_pa_10  away_rolling_win_pct_10  home_qb_completion_pct  away_qb_completion_pct home_win home_team_ARI home_team_ATL home_team_BAL home_team_BUF home_team_CAR home_team_CHI home_team_CIN home_team_CLE home_team_DAL home_team_DEN home_team_DET home_team_GB home_team_HOU home_team_IND home_team_JAX home_team_KC home_team_LAC home_team_LAR home_team_LV home_team_MIA home_team_MIN home_team_NE home_team_NO home_team_NYG home_team_NYJ home_team_PHI home_team_PIT home_team_SEA home_team_SF home_team_TB home_team_TEN home_team_WAS away_team_ARI away_team_ATL away_team_BAL away_team_BUF away_team_CAR away_team_CHI away_team_CIN away_team_CLE away_team_DAL away_team_DEN away_team_DET away_team_GB away_team_HOU away_team_IND away_team_JAX away_team_KC away_team_LAC away_team_LAR away_team_LV away_team_MIA away_team_MIN away_team_NE away_team_NO away_team_NYG away_team_NYJ away_team_PHI away_team_PIT away_team_SEA away_team_SF away_team_TB away_team_TEN away_team_WAS
0  2025.0  18.0   2025_18_ARI_LA     2026-01-04       LAR       ARI              NaN              NaN         NaN    NaN            34.000000            33.000000              0.333333                   -26.000000                   -22.333333                 -0.166667                48.500000                8.333333                6.333333                       0.000000                       0.000000                         0.000000                        0.000000                               0.000000                                 0.000000                       0.000000                        0.000000                 35.0                 29.4                   0.4                       -230.6                        147.6                      -4.0                     47.9                     7.8                     6.4                       0.000000                       0.000000                         0.000000                        0.000000                               0.000000                                 0.000000                       0.000000                        0.000000            17.666667            34.333333              0.000000                   194.000000                  -282.000000                  5.000000                47.833333                8.000000                7.000000                       0.247021                       0.569767                         0.069767                        0.000000                               0.489362                                 0.063830                       0.043393                        0.031915                 17.4                 33.6                   0.0                         49.2                       -132.8                       2.0                     47.5                     7.6                     7.0                       0.101306                       0.525167                         0.056111                        0.017342                               0.467750                                 0.065721                      -0.029725                        0.010638                 16.333333                 -1.333333                   0.333333                       -220.000000                        259.666667                      -5.166667                      0.666667                     0.333333                    -0.666667                                 NaN                                 NaN                                   NaN                                  NaN                                         NaN                                           NaN                                 NaN                                  NaN                      17.6                      -4.2                        0.4                            -279.8                             280.4                           -6.0                           0.4                          0.2                         -0.6                                 NaN                                 NaN                                   NaN                                  NaN                                         NaN                                           NaN                                 NaN                                  NaN             0.789474             0.253165             0.536309          7.5        46.5        6.0        7.0       -1.0                             NaN                           NaN                              NaN                           NaN                                 NaN                             NaN                           NaN                             NaN                                  NaN                          NaN                             NaN                                  NaN                                NaN                             NaN                           NaN                              NaN                           NaN                                 NaN                             NaN                           NaN                             NaN                                  NaN                          NaN                             NaN                                  NaN                                NaN          True   1606.050305   1325.747901    280.302404    1606.050305    1325.747901  202518.0          34.000000          33.000000                0.333333               35.0               29.4                     0.4                34.1                21.6                      0.7          17.666667          34.333333                0.000000               17.4               33.6                     0.0                20.5                32.4                      0.1                     NaN                     NaN      NaN         False         False         False         False         False         False         False         False         False         False         False        False         False         False         False        False         False          True        False         False         False        False        False         False         False         False         False         False        False        False         False         False          True         False         False         False         False         False         False         False         False         False         False        False         False         False         False        False         False         False        False         False         False        False        False         False         False         False         False         False        False        False         False         False
1  2025.0  18.0  2025_18_BAL_PIT     2026-01-04       PIT       BAL              NaN              NaN         NaN    NaN            21.000000            17.333333              0.666667                    90.000000                  -143.333333                  2.000000                43.500000                7.000000                7.333333                       0.036903                       0.422023                         0.055759                        0.007937                               0.522222                                 0.050000                      -0.128467                        0.011111                 19.4                 20.0                   0.6                         64.8                       -112.0                       1.7                     43.7                     7.6                     7.8                       0.076494                       0.409836                         0.098361                        0.000000                               0.522222                                 0.100000                      -0.199139                        0.000000            29.666667            17.333333              0.666667                    37.333333                   -63.666667                  1.166667                46.166667                6.666667                7.000000                       0.140593                       0.503206                         0.106723                        0.015873                               0.428653                                 0.062923                       0.022176                        0.008658                 25.0                 22.2                   0.4                        125.4                       -167.2                       3.2                     46.9                     6.2                     7.0                       0.164318                       0.525397                         0.107143                        0.023810                               0.474149                                 0.068411                      -0.092766                        0.000000                 -8.666667                  0.000000                   0.000000                         52.666667                        -79.666667                       0.833333                     -2.666667                     0.333333                     0.333333                                 NaN                                 NaN                                   NaN                                  NaN                                         NaN                                           NaN                                 NaN                                  NaN                      -5.6                      -2.2                        0.2                             -60.6                              55.2                           -1.5                          -3.2                          1.4                          0.8                                 NaN                                 NaN                                   NaN                                  NaN                                         NaN                                           NaN                                 NaN                                  NaN             0.384615             0.657534            -0.272919         -3.5        41.5        7.0        8.0       -1.0                             NaN                           NaN                              NaN                           NaN                                 NaN                             NaN                           NaN                             NaN                                  NaN                          NaN                             NaN                                  NaN                                NaN                             NaN                           NaN                              NaN                           NaN                                 NaN                             NaN                           NaN                             NaN                                  NaN                          NaN                             NaN                                  NaN                                NaN          True   1552.180626   1595.170818    -42.990192    1552.180626    1595.170818  202518.0          21.000000          17.333333                0.666667               19.4               20.0                     0.6                22.1                22.3                      0.5          29.666667          17.333333                0.666667               25.0               22.2                     0.4                25.6                17.8                      0.7                     NaN                     NaN      NaN         False         False         False         False         False         False         False         False         False         False         False        False         False         False         False        False         False         False        False         False         False        False        False         False         False         False          True         False        False        False         False         False         False         False          True         False         False         False         False         False         False         False         False        False         False         False         False        False         False         False        False         False         False        False        False         False         False         False         False         False        False        False         False         False

In [13]:
from datetime import datetime, timezone

yyyymmdd = datetime.now(timezone.utc).strftime("%Y%m%d")
print(yyyymmdd)

20260104

In [ ]:
from pathlib import Path
import pandas as pd
  
DATASETS_DIR = Path(r"C:\\Users\\goku\\Documents\\NFL_ML_Predictions\\backend\\data\\datasets")

def load_latest_by_filename_date(
    datasets_dir: Path = DATASETS_DIR,
    prefix: str = "game_features_",
) -> tuple[pd.DataFrame, Path]:
    """
    Load the CSV with the largest YYYYMMDD date found in its filename.

    Expected filename format:
      game_features_YYYYMMDD.csv

    Why this works well:
    - Ignores accidental re-saves / modified times
    - Picks the newest dataset by its intended date stamp
    """
    # Example match: game_features_20260103.csv
    files = list(datasets_dir.glob(f"{prefix}*.csv"))

    if not files:
        raise FileNotFoundError(f"No files matched '{prefix}*.csv' in: {datasets_dir}")

    def extract_yyyymmdd(path: Path) -> int:
        """
        Pull YYYYMMDD from 'game_features_YYYYMMDD.csv' -> int(YYYYMMDD).
        If the filename doesn't match, return -1 so it won't win.
        """
        # path.stem is filename without extension: "game_features_20260103"
        suffix = path.stem.replace(prefix, "")

        # Only accept exactly 8 digits for YYYYMMDD
        if len(suffix) == 8 and suffix.isdigit():
            return int(suffix)

        return -1

    # Find the file with the largest date stamp
    latest_file = max(files, key=extract_yyyymmdd)

    # Guard: if all files were invalid format, max() would return one with -1
    if extract_yyyymmdd(latest_file) == -1:
        raise ValueError(
            f"Found CSVs, but none matched '{prefix}YYYYMMDD.csv' in: {datasets_dir}"
        )

    df = pd.read_csv(latest_file)
    df = df.sort_values(["season", "week"], ascending=[False, False])
    return df, latest_file


df, path = load_latest_by_filename_date()
print("Loaded:", path)
print(df.head())

Loaded: C:\Users\goku\Documents\NFL_ML_Predictions\backend\data\datasets\game_features_20260102.csv
      season  week          game_id home_game_date home_team away_team  home_points_for  away_points_for  point_diff winner  home_prior_pf_avg_3  home_prior_pa_avg_3  home_prior_win_pct_3  home_prior_away_moneyline_3  home_prior_home_moneyline_3  home_prior_spread_line_3  home_prior_total_line_3  home_prior_away_rest_3  home_prior_home_rest_3  home_prior_off_epa_per_play_3  home_prior_off_success_rate_3  home_prior_off_explosive_rate_3  home_prior_off_turnover_rate_3  home_prior_def_success_rate_allowed_3  home_prior_def_explosive_rate_allowed_3  home_prior_def_epa_per_play_3  home_prior_def_takeaway_rate_3  home_prior_pf_avg_5  home_prior_pa_avg_5  home_prior_win_pct_5  home_prior_away_moneyline_5  home_prior_home_moneyline_5  home_prior_spread_line_5  home_prior_total_line_5  home_prior_away_rest_5  home_prior_home_rest_5  home_prior_off_epa_per_play_5  home_prior_off_success_rate_5  home_prior_off_explosive_rate_5  home_prior_off_turnover_rate_5  home_prior_def_success_rate_allowed_5  home_prior_def_explosive_rate_allowed_5  home_prior_def_epa_per_play_5  home_prior_def_takeaway_rate_5  away_prior_pf_avg_3  away_prior_pa_avg_3  away_prior_win_pct_3  away_prior_away_moneyline_3  away_prior_home_moneyline_3  away_prior_spread_line_3  away_prior_total_line_3  away_prior_away_rest_3  away_prior_home_rest_3  away_prior_off_epa_per_play_3  away_prior_off_success_rate_3  away_prior_off_explosive_rate_3  away_prior_off_turnover_rate_3  away_prior_def_success_rate_allowed_3  away_prior_def_explosive_rate_allowed_3  away_prior_def_epa_per_play_3  away_prior_def_takeaway_rate_3  away_prior_pf_avg_5  away_prior_pa_avg_5  away_prior_win_pct_5  away_prior_away_moneyline_5  away_prior_home_moneyline_5  away_prior_spread_line_5  away_prior_total_line_5  away_prior_away_rest_5  away_prior_home_rest_5  away_prior_off_epa_per_play_5  away_prior_off_success_rate_5  away_prior_off_explosive_rate_5  away_prior_off_turnover_rate_5  away_prior_def_success_rate_allowed_5  away_prior_def_explosive_rate_allowed_5  away_prior_def_epa_per_play_5  away_prior_def_takeaway_rate_5  home_minus_away_pf_avg_3  home_minus_away_pa_avg_3  home_minus_away_win_pct_3  home_minus_away_away_moneyline_3  home_minus_away_home_moneyline_3  home_minus_away_spread_line_3  home_minus_away_total_line_3  home_minus_away_away_rest_3  home_minus_away_home_rest_3  home_minus_away_off_epa_per_play_3  home_minus_away_off_success_rate_3  home_minus_away_off_explosive_rate_3  home_minus_away_off_turnover_rate_3  home_minus_away_def_success_rate_allowed_3  home_minus_away_def_explosive_rate_allowed_3  home_minus_away_def_epa_per_play_3  home_minus_away_def_takeaway_rate_3  home_minus_away_pf_avg_5  home_minus_away_pa_avg_5  home_minus_away_win_pct_5  home_minus_away_away_moneyline_5  home_minus_away_home_moneyline_5  home_minus_away_spread_line_5  home_minus_away_total_line_5  home_minus_away_away_rest_5  home_minus_away_home_rest_5  home_minus_away_off_epa_per_play_5  home_minus_away_off_success_rate_5  home_minus_away_off_explosive_rate_5  home_minus_away_off_turnover_rate_5  home_minus_away_def_success_rate_allowed_5  home_minus_away_def_explosive_rate_allowed_5  home_minus_away_def_epa_per_play_5  home_minus_away_def_takeaway_rate_5  home_moneyline_prob  away_moneyline_prob  moneyline_prob_diff  spread_line  total_line  home_rest  away_rest  rest_diff  home_player_team_qb_pass_yards  home_player_team_qb_pass_tds  home_player_team_qb_completions  home_player_team_qb_attempts  home_player_team_qb_completion_pct  home_player_team_rb_rush_yards  home_player_team_rb_rush_tds  home_player_team_rb_receptions  home_player_team_rb_receiving_yards  home_player_team_wr_targets  home_player_team_wr_receptions  home_player_team_wr_receiving_yards  home_player_team_wr_receiving_tds  away_player_team_qb_pass_yards  away_player_team_qb_pass_tds  away_player_team_qb_completions  away_player_team_qb_attempts  away_player_team_qb_completion_pct  away_player_team_rb_rush_yards  away_player_team_rb_rush_tds  away_player_team_rb_receptions  away_player_team_rb_receiving_yards  away_player_team_wr_targets  away_player_team_wr_receptions  away_player_team_wr_receiving_yards  away_player_team_wr_receiving_tds has_home_team  home_elo_pre  away_elo_pre  elo_diff_pre  home_elo_post  away_elo_post  time_key  home_rolling_pf_3  home_rolling_pa_3  home_rolling_win_pct_3  home_rolling_pf_5  home_rolling_pa_5  home_rolling_win_pct_5  home_rolling_pf_10  home_rolling_pa_10  home_rolling_win_pct_10  away_rolling_pf_3  away_rolling_pa_3  away_rolling_win_pct_3  away_rolling_pf_5  away_rolling_pa_5  away_rolling_win_pct_5  away_rolling_pf_10  away_rolling_pa_10  away_rolling_win_pct_10  home_qb_completion_pct  away_qb_completion_pct home_win home_team_ARI home_team_ATL home_team_BAL home_team_BUF home_team_CAR home_team_CHI home_team_CIN home_team_CLE home_team_DAL home_team_DEN home_team_DET home_team_GB home_team_HOU home_team_IND home_team_JAX home_team_KC home_team_LAC home_team_LAR home_team_LV home_team_MIA home_team_MIN home_team_NE home_team_NO home_team_NYG home_team_NYJ home_team_PHI home_team_PIT home_team_SEA home_team_SF home_team_TB home_team_TEN home_team_WAS away_team_ARI away_team_ATL away_team_BAL away_team_BUF away_team_CAR away_team_CHI away_team_CIN away_team_CLE away_team_DAL away_team_DEN away_team_DET away_team_GB away_team_HOU away_team_IND away_team_JAX away_team_KC away_team_LAC away_team_LAR away_team_LV away_team_MIA away_team_MIN away_team_NE away_team_NO away_team_NYG away_team_NYJ away_team_PHI away_team_PIT away_team_SEA away_team_SF away_team_TB away_team_TEN away_team_WAS
3266  2025.0  18.0   2025_18_ARI_LA     2026-01-04       LAR       ARI              NaN              NaN         NaN    NaN            34.000000            33.000000              0.333333                   -26.000000                   -22.333333                 -0.166667                48.500000                8.333333                6.333333                       0.000000                       0.000000                         0.000000                        0.000000                               0.000000                                 0.000000                       0.000000                        0.000000                 35.0                 29.4                   0.4                       -230.6                        147.6                      -4.0                     47.9                     7.8                     6.4                       0.000000                       0.000000                         0.000000                        0.000000                               0.000000                                 0.000000                       0.000000                        0.000000            17.666667            34.333333              0.000000                   194.000000                  -282.000000                  5.000000                47.833333                8.000000                7.000000                       0.247021                       0.569767                         0.069767                        0.000000                               0.489362                                 0.063830                       0.043393                        0.031915                 17.4                 33.6                   0.0                         49.2                       -132.8                       2.0                     47.5                     7.6                     7.0                       0.101306                       0.525167                         0.056111                        0.017342                               0.467750                                 0.065721                      -0.029725                        0.010638                 16.333333                 -1.333333                   0.333333                       -220.000000                        259.666667                      -5.166667                      0.666667                     0.333333                    -0.666667                                 NaN                                 NaN                                   NaN                                  NaN                                         NaN                                           NaN                                 NaN                                  NaN                      17.6                      -4.2                        0.4                            -279.8                             280.4                           -6.0                           0.4                          0.2                         -0.6                                 NaN                                 NaN                                   NaN                                  NaN                                         NaN                                           NaN                                 NaN                                  NaN             0.789474             0.253165             0.536309          7.5        46.5        6.0        7.0       -1.0                             NaN                           NaN                              NaN                           NaN                                 NaN                             NaN                           NaN                             NaN                                  NaN                          NaN                             NaN                                  NaN                                NaN                             NaN                           NaN                              NaN                           NaN                                 NaN                             NaN                           NaN                             NaN                                  NaN                          NaN                             NaN                                  NaN                                NaN          True   1606.050305   1325.747901    280.302404    1606.050305    1325.747901  202518.0          34.000000          33.000000                0.333333               35.0               29.4                     0.4                34.1                21.6                      0.7          17.666667          34.333333                0.000000               17.4               33.6                     0.0                20.5                32.4                      0.1                     NaN                     NaN      NaN         False         False         False         False         False         False         False         False         False         False         False        False         False         False         False        False         False          True        False         False         False        False        False         False         False         False         False         False        False        False         False         False          True         False         False         False         False         False         False         False         False         False         False        False         False         False         False        False         False         False        False         False         False        False        False         False         False         False         False         False        False        False         False         False
3267  2025.0  18.0  2025_18_BAL_PIT     2026-01-04       PIT       BAL              NaN              NaN         NaN    NaN            21.000000            17.333333              0.666667                    90.000000                  -143.333333                  2.000000                43.500000                7.000000                7.333333                       0.036903                       0.422023                         0.055759                        0.007937                               0.522222                                 0.050000                      -0.128467                        0.011111                 19.4                 20.0                   0.6                         64.8                       -112.0                       1.7                     43.7                     7.6                     7.8                       0.076494                       0.409836                         0.098361                        0.000000                               0.522222                                 0.100000                      -0.199139                        0.000000            29.666667            17.333333              0.666667                    37.333333                   -63.666667                  1.166667                46.166667                6.666667                7.000000                       0.140593                       0.503206                         0.106723                        0.015873                               0.428653                                 0.062923                       0.022176                        0.008658                 25.0                 22.2                   0.4                        125.4                       -167.2                       3.2                     46.9                     6.2                     7.0                       0.164318                       0.525397                         0.107143                        0.023810                               0.474149                                 0.068411                      -0.092766                        0.000000                 -8.666667                  0.000000                   0.000000                         52.666667                        -79.666667                       0.833333                     -2.666667                     0.333333                     0.333333                                 NaN                                 NaN                                   NaN                                  NaN                                         NaN                                           NaN                                 NaN                                  NaN                      -5.6                      -2.2                        0.2                             -60.6                              55.2                           -1.5                          -3.2                          1.4                          0.8                                 NaN                                 NaN                                   NaN                                  NaN                                         NaN                                           NaN                                 NaN                                  NaN             0.384615             0.657534            -0.272919         -3.5        41.5        7.0        8.0       -1.0                             NaN                           NaN                              NaN                           NaN                                 NaN                             NaN                           NaN                             NaN                                  NaN                          NaN                             NaN                                  NaN                                NaN                             NaN                           NaN                              NaN                           NaN                                 NaN                             NaN                           NaN                             NaN                                  NaN                          NaN                             NaN                                  NaN                                NaN          True   1552.180626   1595.170818    -42.990192    1552.180626    1595.170818  202518.0          21.000000          17.333333                0.666667               19.4               20.0                     0.6                22.1                22.3                      0.5          29.666667          17.333333                0.666667               25.0               22.2                     0.4                25.6                17.8                      0.7                     NaN                     NaN      NaN         False         False         False         False         False         False         False         False         False         False         False        False         False         False         False        False         False         False        False         False         False        False        False         False         False         False          True         False        False        False         False         False         False         False          True         False         False         False         False         False         False         False         False        False         False         False         False        False         False         False        False         False         False        False        False         False         False         False         False         False        False        False         False         False

In [ ]:
import nflreadpy as nfl
import pandas as pd
from pathlib import Path
import glob
import os
from datetime import datetime, timezone

max_col = pd.set_option("display.max_columns", None)
max_rows = pd.set_option("display.max_rows", None)

yyyymmdd = datetime.now(timezone.utc).strftime("%Y%m%d")
season = nfl.get_current_season()
week = nfl.get_current_week()
home_team = "LAR"
away_team = "ARI"

# Function to get the row for a given game by season, week, home_team, away_team
def get_row(df=df, payload={}):
    """Filter df down to the single game row that matches this (season, week, home, away) tuple"""
    df = df.convert_dtypes()
    mask = (
        (df["season"] == season) &
        (df["week"] == week) &
        (df["home_team"] == home_team) &
        (df["away_team"] == away_team)
    )
    game_row = df.loc[mask]
    return game_row



game_row = get_row(df, payload={"season": season, "week": week, "home_team": home_team, "away_team": away_team})

print(game_row)

      season  week         game_id home_game_date home_team away_team  home_points_for  away_points_for  point_diff winner  home_prior_pf_avg_3  home_prior_pa_avg_3  home_prior_win_pct_3  home_prior_away_moneyline_3  home_prior_home_moneyline_3  home_prior_spread_line_3  home_prior_total_line_3  home_prior_away_rest_3  home_prior_home_rest_3  home_prior_off_epa_per_play_3  home_prior_off_success_rate_3  home_prior_off_explosive_rate_3  home_prior_off_turnover_rate_3  home_prior_def_success_rate_allowed_3  home_prior_def_explosive_rate_allowed_3  home_prior_def_epa_per_play_3  home_prior_def_takeaway_rate_3  home_prior_pf_avg_5  home_prior_pa_avg_5  home_prior_win_pct_5  home_prior_away_moneyline_5  home_prior_home_moneyline_5  home_prior_spread_line_5  home_prior_total_line_5  home_prior_away_rest_5  home_prior_home_rest_5  home_prior_off_epa_per_play_5  home_prior_off_success_rate_5  home_prior_off_explosive_rate_5  home_prior_off_turnover_rate_5  home_prior_def_success_rate_allowed_5  home_prior_def_explosive_rate_allowed_5  home_prior_def_epa_per_play_5  home_prior_def_takeaway_rate_5  away_prior_pf_avg_3  away_prior_pa_avg_3  away_prior_win_pct_3  away_prior_away_moneyline_3  away_prior_home_moneyline_3  away_prior_spread_line_3  away_prior_total_line_3  away_prior_away_rest_3  away_prior_home_rest_3  away_prior_off_epa_per_play_3  away_prior_off_success_rate_3  away_prior_off_explosive_rate_3  away_prior_off_turnover_rate_3  away_prior_def_success_rate_allowed_3  away_prior_def_explosive_rate_allowed_3  away_prior_def_epa_per_play_3  away_prior_def_takeaway_rate_3  away_prior_pf_avg_5  away_prior_pa_avg_5  away_prior_win_pct_5  away_prior_away_moneyline_5  away_prior_home_moneyline_5  away_prior_spread_line_5  away_prior_total_line_5  away_prior_away_rest_5  away_prior_home_rest_5  away_prior_off_epa_per_play_5  away_prior_off_success_rate_5  away_prior_off_explosive_rate_5  away_prior_off_turnover_rate_5  away_prior_def_success_rate_allowed_5  away_prior_def_explosive_rate_allowed_5  away_prior_def_epa_per_play_5  away_prior_def_takeaway_rate_5  home_minus_away_pf_avg_3  home_minus_away_pa_avg_3  home_minus_away_win_pct_3  home_minus_away_away_moneyline_3  home_minus_away_home_moneyline_3  home_minus_away_spread_line_3  home_minus_away_total_line_3  home_minus_away_away_rest_3  home_minus_away_home_rest_3  home_minus_away_off_epa_per_play_3  home_minus_away_off_success_rate_3  home_minus_away_off_explosive_rate_3  home_minus_away_off_turnover_rate_3  home_minus_away_def_success_rate_allowed_3  home_minus_away_def_explosive_rate_allowed_3  home_minus_away_def_epa_per_play_3  home_minus_away_def_takeaway_rate_3  home_minus_away_pf_avg_5  home_minus_away_pa_avg_5  home_minus_away_win_pct_5  home_minus_away_away_moneyline_5  home_minus_away_home_moneyline_5  home_minus_away_spread_line_5  home_minus_away_total_line_5  home_minus_away_away_rest_5  home_minus_away_home_rest_5  home_minus_away_off_epa_per_play_5  home_minus_away_off_success_rate_5  home_minus_away_off_explosive_rate_5  home_minus_away_off_turnover_rate_5  home_minus_away_def_success_rate_allowed_5  home_minus_away_def_explosive_rate_allowed_5  home_minus_away_def_epa_per_play_5  home_minus_away_def_takeaway_rate_5  home_moneyline_prob  away_moneyline_prob  moneyline_prob_diff  spread_line  total_line  home_rest  away_rest  rest_diff  home_player_team_qb_pass_yards  home_player_team_qb_pass_tds  home_player_team_qb_completions  home_player_team_qb_attempts  home_player_team_qb_completion_pct  home_player_team_rb_rush_yards  home_player_team_rb_rush_tds  home_player_team_rb_receptions  home_player_team_rb_receiving_yards  home_player_team_wr_targets  home_player_team_wr_receptions  home_player_team_wr_receiving_yards  home_player_team_wr_receiving_tds  away_player_team_qb_pass_yards  away_player_team_qb_pass_tds  away_player_team_qb_completions  away_player_team_qb_attempts  away_player_team_qb_completion_pct  away_player_team_rb_rush_yards  away_player_team_rb_rush_tds  away_player_team_rb_receptions  away_player_team_rb_receiving_yards  away_player_team_wr_targets  away_player_team_wr_receptions  away_player_team_wr_receiving_yards  away_player_team_wr_receiving_tds  has_home_team  home_elo_pre  away_elo_pre  elo_diff_pre  home_elo_post  away_elo_post  time_key  home_rolling_pf_3  home_rolling_pa_3  home_rolling_win_pct_3  home_rolling_pf_5  home_rolling_pa_5  home_rolling_win_pct_5  home_rolling_pf_10  home_rolling_pa_10  home_rolling_win_pct_10  away_rolling_pf_3  away_rolling_pa_3  away_rolling_win_pct_3  away_rolling_pf_5  away_rolling_pa_5  away_rolling_win_pct_5  away_rolling_pf_10  away_rolling_pa_10  away_rolling_win_pct_10  home_qb_completion_pct  away_qb_completion_pct  home_win  home_team_ARI  home_team_ATL  home_team_BAL  home_team_BUF  home_team_CAR  home_team_CHI  home_team_CIN  home_team_CLE  home_team_DAL  home_team_DEN  home_team_DET  home_team_GB  home_team_HOU  home_team_IND  home_team_JAX  home_team_KC  home_team_LAC  home_team_LAR  home_team_LV  home_team_MIA  home_team_MIN  home_team_NE  home_team_NO  home_team_NYG  home_team_NYJ  home_team_PHI  home_team_PIT  home_team_SEA  home_team_SF  home_team_TB  home_team_TEN  home_team_WAS  away_team_ARI  away_team_ATL  away_team_BAL  away_team_BUF  away_team_CAR  away_team_CHI  away_team_CIN  away_team_CLE  away_team_DAL  away_team_DEN  away_team_DET  away_team_GB  away_team_HOU  away_team_IND  away_team_JAX  away_team_KC  away_team_LAC  away_team_LAR  away_team_LV  away_team_MIA  away_team_MIN  away_team_NE  away_team_NO  away_team_NYG  away_team_NYJ  away_team_PHI  away_team_PIT  away_team_SEA  away_team_SF  away_team_TB  away_team_TEN  away_team_WAS
3266    2025    18  2025_18_ARI_LA     2026-01-04       LAR       ARI             <NA>             <NA>        <NA>   <NA>                 34.0                 33.0              0.333333                        -26.0                   -22.333333                 -0.166667                     48.5                8.333333                6.333333                            0.0                            0.0                              0.0                             0.0                                    0.0                                      0.0                            0.0                             0.0                 35.0                 29.4                   0.4                       -230.6                        147.6                      -4.0                     47.9                     7.8                     6.4                            0.0                            0.0                              0.0                             0.0                                    0.0                                      0.0                            0.0                             0.0            17.666667            34.333333                   0.0                        194.0                       -282.0                       5.0                47.833333                     8.0                     7.0                       0.247021                       0.569767                         0.069767                             0.0                               0.489362                                  0.06383                       0.043393                        0.031915                 17.4                 33.6                   0.0                         49.2                       -132.8                       2.0                     47.5                     7.6                     7.0                       0.101306                       0.525167                         0.056111                        0.017342                                0.46775                                 0.065721                      -0.029725                        0.010638                 16.333333                 -1.333333                   0.333333                            -220.0                        259.666667                      -5.166667                      0.666667                     0.333333                    -0.666667                                <NA>                                <NA>                                  <NA>                                 <NA>                                        <NA>                                          <NA>                                <NA>                                 <NA>                      17.6                      -4.2                        0.4                            -279.8                             280.4                           -6.0                           0.4                          0.2                         -0.6                                <NA>                                <NA>                                  <NA>                                 <NA>                                        <NA>                                          <NA>                                <NA>                                 <NA>             0.789474             0.253165             0.536309          7.5        46.5          6          7         -1                            <NA>                          <NA>                             <NA>                          <NA>                                <NA>                            <NA>                          <NA>                            <NA>                                 <NA>                         <NA>                            <NA>                                 <NA>                               <NA>                            <NA>                          <NA>                             <NA>                          <NA>                                <NA>                            <NA>                          <NA>                            <NA>                                 <NA>                         <NA>                            <NA>                                 <NA>                               <NA>           True   1606.050305   1325.747901    280.302404    1606.050305    1325.747901    202518               34.0               33.0                0.333333               35.0               29.4                     0.4                34.1                21.6                      0.7          17.666667          34.333333                     0.0               17.4               33.6                     0.0                20.5                32.4                      0.1                    <NA>                    <NA>      <NA>          False          False          False          False          False          False          False          False          False          False          False         False          False          False          False         False          False           True         False          False          False         False         False          False          False          False          False          False         False         False          False          False           True          False          False          False          False          False          False          False          False          False          False         False          False          False          False         False          False          False         False          False          False         False         False          False          False          False          False          False         False         False          False          False

In [ ]:

def get_row(df=df, season=season, week=week, home_team=home_team, away_team=away_team):
    return _find_dataset_row(df, season=season, week=week, home_team=home_team, away_team=away_team)

print(get_row())